### ISSUE TITLE
Add Delete Role API

### ISSUE THREAD

**Issue by sanjaysah101** [ansopedia/users#56]
## Description:

We need to add functionality for deleting roles in the `user-service`. This API should follow specific constraints to ensure that system-defined roles (default roles) are not deleted, while roles created by users can be deleted under the right conditions.

### 1. Role Deletion Constraints

- Default roles **cannot** be deleted.
- Only user-created roles should be deletable.
- Add a boolean flag `canBeDeleted` in the `Role` model to mark which roles are deletable.

### 2. Authentication & Authorization:

- Use the existing `validateAccessToken` middleware to authenticate the user.
- Use `checkPermission(['delete-roles'])` to authorize users with the right permissions to delete roles.

### 3. API Endpoint:

- Create a new `DELETE /roles/:roleId` route to handle role deletion.

### 4. Controller Layer:

- Create a `deleteRole` method in the controller to handle the incoming request for role deletion.

### 5. Service Layer:

- Implement business logic in the service layer through a new `deleteRole` method.
- Ensure that deletion is allowed only if the `canBeDeleted` flag is `true`.

### 6. Data Access Layer (DAL):

- Add a `deleteRole` method in the DAL to perform the actual deletion of the role in the database.

### 7. Validation:

- Update the `role.validation.ts` file to handle any necessary validation for role deletion, including checking the `canBeDeleted` flag.

### 8. Existing Code Reference:

The new route and functionality should be consistent with existing routes such as:

```javascript
router.delete('/roles', validateAccessToken, checkPermission(['delete-roles']), deleteRole);
```

### 9. Tests:

Write unit tests to cover:

## Tasks:

- [ ] Add a `canBeDeleted` flag in the `Role` model.
- [x] Create a new `DELETE /roles/:roleId` endpoint in the router.
- [x] Add `deleteRole` method in the **controller**.
- [x] Add `deleteRole` method in the **service**.
- [ ] Add `deleteRole` method in the **DAL**.
- [ ] Ensure that only roles with `canBeDeleted = true` can be deleted.
- [ ] Use `validateAccessToken` to authenticate the user.
- [ ] Use `checkPermission(['delete-roles'])` to authorize the user.
- [ ] Update `role.validation.ts` with any necessary validation logic.
- [ ] Write unit tests for this new functionality.

## Acceptance Criteria:

- Default roles are protected from deletion.
- User-created roles can be deleted if `canBeDeleted` is `true`.
- API is secure with proper authentication and authorization in place.
- All tests pass.

**Comment by abhishek-nexgen-dev** [comment]
I am Interested to code this

**Comment by sanjaysah101** [comment]
> I am Interested to code this

Yes please

**Comment by abhishek-nexgen-dev** [comment]
> > I am Interested to code this

>  By default the The Value of canBeDeleted Deleted is false . If user Is proper authenticated then you want to Update the  canBeDeleted  = true . If i am not Correct then Please Describe me In detail .

**Comment by sanjaysah101** [comment]
Hi @Code-With-Abhishek-Kumar, As you can see in `role.model.ts` file there is `isSystemRole`. Instead of adding extra flag, we can use `isSystemRole` flag. 

Edge Case: 
- If isSystemRole is true then do not allow delete
- Add `SYSTEM_ROLE_CANNOT_BE_DELETED` in `error-types.constant.ts` file

let me know if you have any doubt.

**Comment by abhishek-nexgen-dev** [comment]
> Hi @Code-With-Abhishek-Kumar, As you can see in `role.model.ts` file there is `isSystemRole`. Instead of adding extra flag, we can use `isSystemRole` flag.
> 
> Edge Case:
> 
>     * If isSystemRole is true then do not allow delete
> 
>     * Add `SYSTEM_ROLE_CANNOT_BE_DELETED` in `error-types.constant.ts` file
> 
> 
> let me know if you have any doubt.

Okay Got it

**Comment by abhishek-nexgen-dev** [comment]
> Hi @Code-With-Abhishek-Kumar, As you can see in `role.model.ts` file there is `isSystemRole`. Instead of adding extra flag, we can use `isSystemRole` flag.
> 
> Edge Case:
> 
>     * If isSystemRole is true then do not allow delete
> 
>     * Add `SYSTEM_ROLE_CANNOT_BE_DELETED` in `error-types.constant.ts` file
> 
> 
> let me know if you have any doubt.

How can i pass These Credential so that i can test application in my local

 
![Screenshot at 2025-01-14 12-22-28](https://github.com/user-attachments/assets/d54817e1-68ce-4592-bc03-06af1e5a2098)

**Comment by sanjaysah101** [comment]
Hi @Code-With-Abhishek-Kumar,  

Please follow these steps to set up the project:  

1. Pull the latest changes from the repository.  
2. Copy the content from `env.example` to `.env`.  
3. Install the required packages.  
4. Run the command `pnpm generate-keys` to generate RSA keys.  
5. Copy both the public and private keys to the `.env` file.  
6. Execute `pnpm test` to run the test suite.  

Once all the test cases pass, the project setup is complete.

**Comment by abhishek-nexgen-dev** [comment]
> Hi @sanjaysah101 
,
>  I am Getting Error When I Try To run pnpm test  

![Screenshot at 2025-01-15 09-48-35](https://github.com/user-attachments/assets/fdba142d-f100-49a8-ab49-ec404611db9d)

![Screenshot at 2025-01-15 09-49-12](https://github.com/user-attachments/assets/4149e857-dfa2-4336-a595-5a3899adfc4c)

**Comment by sanjaysah101** [comment]
This means the env constant has not been set correctly. Please refer `Readme.md` file.
