### ISSUE TITLE
BE - Add Create Profile API

### ISSUE THREAD

**Issue by sanjaysah101** [ansopedia/users#60]
## Description:

We need to implement the user profile management functionality in the user-service, allowing authenticated users to create and manage their profiles.

---

## Key Requirements:

1. Profile Creation API:
   - Implement the `POST /profile` route to allow users to create their profiles.
   - Example:
     ```ts
     router.post('/profile', validateAccessToken, ProfileController.createProfile);
     ```
   - Ensure the user is authenticated using the `validateAccessToken` middleware.
2. Profile Folder Structure:
   Follow the folder structure for organizing the profile-related code:

   ```
   src
       - v1
           - profile
               - profile.route.ts
               - profile.controller.ts
               - profile.service.ts
               - profile.validation.ts
               - profile.constant.ts
               - profile.dal.ts
               - profile.model.ts
   ```

3. Zod for Profile Validation:

   - Use **Zod** to create the profile schema for validation.
   - Generate the profile schema type like `ProfileData` inside `profile.validation.ts`.
   - Example Zod schema:

     ```ts
     import { z } from 'zod';

     export const profileSchema = z.object({
       userId: objectIdSchema,
       bio: z.string().optional().max(500),
       profilePictureUrl: z.string().url().optional(),
       address: z
         .object({
           street: z.string().optional(),
           city: z.string().optional(),
           country: z.string().optional(),
           zipCode: z.string().optional(),
         })
         .optional(),
       phoneNumber: z.string().optional(),
       socialLinks: z
         .object({
           twitter: z.string().url().optional(),
           linkedin: z.string().url().optional(),
           github: z.string().url().optional(),
         })
         .optional(),
     });

     export type ProfileData = z.infer<typeof profileSchema>;
     ```

4. User Schema:
   The profile schema should reference the `userId` from the existing User Schema.

   - Add a reference to the `userId` in the profile model as follows:
     ```ts
      userId: {
      type: String,
      required: true,
      validate: {
        validator: (v: string) => Types.ObjectId.isValid(v),
        message: 'userId must be a valid MongoDB ObjectId string',
      },
      ref: 'User',
     },
     ```

5. Test Cases:
   Write unit tests for the following scenarios:
   - **Profile Creation**: Test successful profile creation.
   - **Profile Validation**: Ensure invalid profile data is rejected.
   - **Authentication**: Verify that only authenticated users can create profiles.

### **Tasks:**

- [x] Add Zod-based validation in `profile.validation.ts` and generate types.
- [x] Create `profile.model.ts` for the Profile schema.
- [x] Create `POST /profile` inside `profile.route.ts` for the Profile routes.
- [x] Implement `ProfileController.createProfile` method.
- [x] Create and implement `ProfileService` for handling profile-related logic.
- [x] Add `validateAccessToken` middleware for user authentication.
- [x] Write test cases for the profile routes using your preferred testing framework.

Related to: #19
