### ISSUE TITLE
BE - Create Get Profile Data API

### ISSUE THREAD

**Issue by sanjaysah101** [ansopedia/users#61]
## Description:

We need to implement the functionality that allows authenticated users to retrieve their profile information. This API will return the user’s profile data if it exists, ensuring secure access. 

## Key Requirements:

1. Get Profile API:

   - Implement the `GET /profile` route to allow users to retrieve their profile data.
   - Example:
     ```ts
     router.get('/profile', validateAccessToken, ProfileController.getProfile);
     ```
   - Ensure the user is authenticated using the `validateAccessToken` middleware. 

2. Profile Folder Structure:
   The folder structure for organizing the profile-related code should follow:

   ```
   src
       - v1
           - profile
               - profile.route.ts
               - profile.controller.ts
               - profile.service.ts
               - profile.validation.ts
               - profile.constant.ts
               - profile.dal.ts
               - profile.model.ts
   ```

3. Profile Service Logic:

   - Implement a `getProfileByUserId` method inside `ProfileService` to fetch the user’s profile data by their `userId`.
   - If the profile does not exist, return a `404 Not Found` response.

4. Zod for Profile Data Validation:

   - Reuse the **Zod** profile schema for validating the returned profile data structure.
   - Ensure that types generated in `profile.validation.ts` match the data returned by the API.

5. User Schema Reference:

   - The **Profile Schema** should reference the `userId` from the existing User Schema to retrieve data.
   - Example:
     ```ts
     userId: { type: Schema.Types.ObjectId, ref: 'User', required: true, unique: true }
     ```

6. Test Cases:
   Write unit tests for the following scenarios:
   - **Profile Retrieval Success**: Test that the profile data is successfully retrieved for authenticated users.
   - **Profile Not Found**: Test that a `404 Not Found` error is returned when a profile does not exist.
   - **Authentication**: Verify that only authenticated users can access the API.

## Tasks:

- [x] Create the `getProfileByUserId` method in `ProfileService`.
- [x] Implement the `ProfileController.getProfile` method.
- [x] Add the `GET /profile` route in `profile.route.ts`.
- [x] Ensure `validateAccessToken` middleware is added to protect the route.
- [ ] Write test cases for:
  - **Successful Profile Retrieval**: Test when the profile exists.
  - **Profile Not Found**: Test when the profile does not exist.
  - **Authentication Check**: Test unauthorized access is rejected.
  
  #19, #60
