### ISSUE TITLE
BE - Create Update Profile Data API

### ISSUE THREAD

**Issue by sanjaysah101** [ansopedia/users#62]
## Description:

We need to implement the functionality that allows authenticated users to update their profile information. The API should ensure validation of the input data and secure access, allowing users to modify only their profile.

---

## Key Requirements:

1. **Update Profile API:**

   - Implement the `PUT /profile` route to allow users to update their profile information.
   - Example:
     ```ts
     router.put('/profile', validateAccessToken, ProfileController.updateProfile);
     ```
   - Ensure the user is authenticated using the `validateAccessToken` middleware.

2. **Profile Folder Structure:**
   The folder structure for organizing profile-related code should follow:

   ```
   src
       - v1
           - profile
               - profile.route.ts
               - profile.controller.ts
               - profile.service.ts
               - profile.validation.ts
               - profile.constant.ts
               - profile.dal.ts
               - profile.model.ts
   ```

3. **Profile Service Logic:**

   - Implement an `updateProfile` method inside `ProfileService` to handle updating the profile based on `userId`.
   - Ensure partial updates (e.g., updating just the bio, or address) can be made without overwriting the entire profile.
   - Return appropriate status codes for successful updates or errors.

4. **Zod for Update Profile Validation:**

   - Reuse the **Zod** profile schema to validate the updated data.
   - Generate the updated profile schema type inside `profile.validation.ts` for validation during updates.

   Example:

   ```ts
   export const updateProfileSchema = profileSchema.partial();
   ```

5. **User Schema Reference:**

   - The **Profile Schema** should reference the `userId` from the User Schema, and ensure that users can only update their profile data.
   - Example:
     ```ts
     userId: { type: Schema.Types.ObjectId, ref: 'User', required: true, unique: true }
     ```

6. **Test Cases:**
   Write unit tests for the following scenarios:
   - **Profile Update Success**: Test that users can successfully update their profile.
   - **Invalid Data**: Ensure the validation schema rejects invalid data.
   - **Profile Not Found**: Return a `404 Not Found` error if the profile doesn't exist.
   - **Authentication**: Verify that only authenticated users can update their profiles.

### **Tasks:**

- [x] Implement the `updateProfile` method in `ProfileService` to handle profile updates.
- [x] Add `ProfileController.updateProfile` method in `profile.controller.ts`.
- [x] Add the `PUT /profile` route in `profile.route.ts`.
- [x] Use `validateAccessToken` middleware to protect the update profile route.
- [x] Add **Zod** validation for the update profile data using `profile.validation.ts`.
- [x] Write test cases for:
  - **Successful Profile Update**: Ensure valid updates are handled correctly.
  - **Invalid Data**: Reject invalid data based on Zod validation schema.
  - **Profile Not Found**: Handle cases where a profile doesn't exist.
  - **Authentication Enforcement**: Ensure only authenticated users can update their profiles.
  
  #19, #60, #61
