### ISSUE TITLE
BE - Store Profile Details from Google Sign-In in Profile Schema

### ISSUE THREAD

**Issue by sanjaysah101** [ansopedia/users#66]
## Description:

Implement functionality to store user profile details fetched from Google during the OAuth 2.0 sign-in process. This will enhance user profiles by automatically populating relevant fields with data obtained from Google, with restrictions on updates only during the first sign-in.

### 1. User Schema:

- Ensure the existing user schema includes the following fields:
  - `userId`
  - `googleId`

### 2. Profile Schema:

- Update the existing profile schema to store the following details fetched from Google:
  ```typescript
  export const profileSchema = z.object({
    userId: objectIdSchema,
    bio: z.string().optional().max(500),
    profilePictureUrl: z.string().url().optional(),
    address: z
      .object({
        street: z.string().optional(),
        city: z.string().optional(),
        country: z.string().optional(),
        zipCode: z.string().optional(),
      })
      .optional(),
    phoneNumber: z.string().optional(),
    socialLinks: z
      .object({
        twitter: z.string().url().optional(),
        linkedin: z.string().url().optional(),
        github: z.string().url().optional(),
      })
      .optional(),
    gender: z.enum(['male', 'female', 'non-binary', 'other']).optional(),
    pronouns: z.enum(['he/him', 'she/her', 'they/them', 'other']).optional(),
  });
  ```

### 3. Fetching and Storing Profile Details:

- After a successful Google sign-in, check for the presence of `googleId` in the user schema:
  - If `googleId` does not exist, it indicates that the user is signing in for the first time. In this case, check if a corresponding user entry already exists in the database.
  - Only update the profile fields if they are empty:
    - Update `profilePictureUrl`, `bio`, `phoneNumber`, `gender`, and `pronouns` only if they are currently undefined or null in the profile.

### 4. Validation:

- Ensure that all fetched fields comply with the validation rules defined in the profile schema.

### 5. Testing:

- Write unit tests to cover the following scenarios:
  - Successful storage of profile details upon Google sign-in.
  - Proper handling of existing users (updating their profile only if fields are empty).
  - Validation checks for fetched data.

### Tasks:

- [ ] Implement logic to check for `googleId` in the user schema upon Google sign-in.
- [ ] Fetch user profile details from Google after OAuth sign-in.
- [ ] Create or update user and profile entries in the database with fetched details, ensuring updates only occur if fields are empty.
- [ ] Ensure validation of profile fields according to the schema.
- [ ] Write unit tests for all scenarios mentioned above.
