### ISSUE TITLE
Implement Pagination for Get Users Request

### ISSUE THREAD

**Issue by sanjaysah101** [ansopedia/users#68]
## Description:

Enhance the `GET /users` route to support pagination by adding `offset` and `limit` parameters. This will limit the number of users fetched in a single request, improving performance and usability.

### 1. Pagination Parameters:

- Accept the following query parameters in the `GET /users` request:
  - `limit`: The maximum number of users to fetch (default value: 10).
  - `offset`: The number of users to skip (default value: 0).

Example request:

```
GET /users?limit=10&offset=0
```

### 2. Implement Pagination Logic:

- Update the `getAllUsers` controller to handle `limit` and `offset`:
  - Use `limit` to restrict the number of users returned.
  - Use `offset` to skip the specified number of users.
- Ensure that both parameters are validated to ensure they are positive integers.

### 3. Response Structure:

- Return a response that includes the total number of users and the paginated user data:
  ```json
  {
    "totalUsers": 100,
    "users": [
      {
        "username": "user1",
        "bio": "User bio here.",
        ...
      },
      ...
    ]
  }
  ```

### 4. Testing:

- Write unit tests to cover the following scenarios:
  - Verify that the correct number of users is returned based on the `limit` parameter.
  - Ensure that the `offset` parameter correctly skips the specified number of users.
  - Confirm that the response structure is as expected.

### Tasks:

- [x] Update the `getAllUsers` controller to implement pagination with `limit` and `offset`.
- [x] Validate `limit` and `offset` parameters in the request.
- [x] Update the response structure to include `totalUsers` and the paginated user data.
- [ ] Write unit tests for all scenarios mentioned above.
