### ISSUE TITLE
BE - Protect Permission Routes

### ISSUE THREAD

**Issue by sanjaysah101** [ansopedia/users#69]
## Description:

Implement access control for user-related routes to ensure that only authenticated users can access them. Specifically, the following routes need to be protected:

- `GET /permissions`

### 1. Authentication Middleware:

- Use the `validateAccessToken` middleware to ensure that only logged-in users can access these routes.

### 2. Route Protection:

- Apply the middleware to the following routes:
  ```javascript
  router.get('/permissions', validateAccessToken, getPermissions);
  ```

3. Remove Route:

   ```javascript
   router.post('/permissions', createPermission);
   ```

### 4. Testing:

- Write unit tests to cover the following scenarios:
  - Verify that authenticated users can access both routes successfully.
  - Ensure that unauthenticated users receive a `401 Unauthorized` response when trying to access these routes.

### Tasks:

- [x] Apply the `validateAccessToken` middleware to the `/permissions`
- [x] Remove `Post /permissions route`
- [x] Ensure proper error handling for unauthorized access.
- [x] Write unit tests for all scenarios mentioned above.
