### ISSUE TITLE
Configure Global Rate Limiting for the Project

### ISSUE THREAD

**Issue by ansopedia** [ansopedia/users#71]
## Description

To enhance security and prevent abuse such as Denial of Service (DoS) attacks, we need to implement rate limiting at the project level. This will ensure that all endpoints are protected with a reasonable request limit per IP address within a specified time window.

We will use the `express-rate-limit` package to achieve this and configure it as a global middleware to apply across all routes.

## Background

Rate limiting is a crucial security measure that helps protect our API from abuse, ensures fair usage, and maintains the stability of our service. By limiting the number of requests a client can make in a given time frame, we can:

1. Prevent brute-force attacks
2. Mitigate the impact of DoS attacks
3. Ensure equitable API access for all users
4. Reduce the load on our servers

## Tasks:

1. **Install `express-rate-limit`**:

   - Run the following command to install the package:
     ```bash
     pnpm install express-rate-limit
     ```

2. **Configure Global Rate Limiter**:

   - Add a rate limiter middleware in `app.ts` (or the main server file) to apply across all routes.
   - Set the limit to **100 requests per 15 minutes**.

   Example:

   ```typescript
   import rateLimit from 'express-rate-limit';

   const globalLimiter = rateLimit({
     windowMs: 15 * 60 * 1000, // 15 minutes
     max: 100, // Limit each IP to 100 requests per windowMs
     standardHeaders: true, // Return rate limit info in the `RateLimit-*` headers
     legacyHeaders: false, // Disable the `X-RateLimit-*` headers
     message: 'Too many requests from this IP, please try again after 15 minutes',
   });

   app.use(globalLimiter); // Apply rate limiting to all requests
   ```

3. **Implement Proper IP Detection**:

   - Ensure that the rate limiter correctly identifies client IPs, especially if the app is behind a reverse proxy.
   - If using a reverse proxy, configure the rate limiter to use the `X-Forwarded-For` header:

   ```typescript
   app.set('trust proxy', 1);
   ```

4. **Test the Rate Limiter**:

   - Ensure that the rate limiter works as expected by making multiple requests to the API and verifying that it blocks requests after the limit is reached.
   - Verify that the appropriate headers (`RateLimit-*`) are included in the response.
   - Test with different endpoints to ensure global application.

5. **Update Documentation**:
   - Update the project documentation to mention the rate-limiting policy, indicating the global limit of 100 requests per 15 minutes.
   - Include information about the rate limit headers in the API documentation.

### Rate Limit Headers

The rate limiter will add the following headers to responses:

- `RateLimit-Limit`: The maximum number of requests allowed in the current time window.
- `RateLimit-Remaining`: The number of requests remaining in the current time window.
- `RateLimit-Reset`: The time (in seconds) when the current rate limit window resets.

These headers provide valuable information to API consumers about their current rate limit status.

### Rate Limit Policy Header

In addition to the `RateLimit-*` headers mentioned earlier, our API will also include a `RateLimit-Policy` header. This header provides a concise representation of the rate limit rules. 

For example:

```
RateLimit-Policy: 100;w=900
```

This means:
- 100 requests are allowed
- Within a window (w) of 900 seconds (15 minutes)

This header helps API consumers quickly understand the rate-limiting rules without needing to consult separate documentation.

Task:
- [ ] Ensure that the `RateLimit-Policy` header is correctly set and reflects our intended rate limit policy.
- [ ] Include information about the `RateLimit-Policy` header in the API documentation.

## Customization Considerations

While implementing global rate limiting, consider the following:

1. **Different limits for different routes**: Some routes may require stricter or more lenient limits. Consider implementing route-specific limiters where necessary.

2. **Whitelist**: Implement a whitelist for trusted IPs or authenticated users who may need higher limits.

3. **Response codes**: Ensure that when the rate limit is exceeded, the API returns a 429 (Too Many Requests) status code.

4. **Monitoring**: Set up monitoring to track rate limit hits and adjust the limits if necessary based on actual usage patterns.

## Acceptance Criteria:

- [ ] `express-rate-limit` is installed and configured as global middleware.
- [ ] All routes are protected by the rate limiter.
- [ ] The limit is set to 100 requests per 15 minutes, and appropriate error messages are returned once the limit is exceeded.
- [ ] Rate limit headers (`RateLimit-*`) are included in API responses.
- [ ] The application correctly identifies client IPs, including when behind a reverse proxy.
- [ ] Tests confirm that rate limiting is working as expected across different endpoints.
- [ ] Documentation is updated to reflect the rate-limiting configuration and includes information about rate limit headers.
